### ISSUE TITLE
`get` not @safe?

### ISSUE THREAD

**Issue by joakim-brannstrom** [submada/autoptr#1]
Hello,

Thank you for the nice library. I'll probably replace my own with yours. You have support for allocators etc which is what I was thinking of adding.

Now on to the question.
Is it possible to make `get` `@safe`?

I tried this code:

```d
void test6() @safe {
    import autoptr.shared_ptr;

    static struct S {
        int x;
    }

    auto a = SharedPtr!S.make(42);
    writeln(*a);
}
```

But got this error message:

```sh
foo.d(33,13): Error: `@safe` function `app.test6` cannot call `@system` function `autoptr.shared_ptr.SharedPtr!(S, void function(Evoid*) pure nothrow @nogc @safe, ControlBlock!(int, int), false).SharedPtr.get`
/home/username/.dub/packages/autoptr-0.4.5-beta/autoptr/src/autoptr/shared_ptr.d(1885,57):        `autoptr.shared_ptr.SharedPtr!(S, void function(Evoid*) pure nothrow @nogc @safe, ControlBlock!(int, int), false).SharedPtr.get` is declared here
```

**Comment by submada** [comment]
Unfortunately `get()`, `opUnary!"*"` or any other function returning reference or pointer to managed data canno't be @safe/@trusted.

Example:
```d
import std.traits : isDynamicArray;

auto trustedGet(Ptr)(ref scope Ptr ptr)@trusted
if(is(Ptr.ElementType == class) || is(Ptr.ElementType == interface) || isDynamicArray!(Ptr.ElementType)){
    return ptr.get();
}

ref auto trustedGet(Ptr)(ref scope Ptr ptr)@trusted
if(!is(Ptr.ElementType == class) && !is(Ptr.ElementType == interface) && !isDynamicArray!(Ptr.ElementType)){
    return ptr.get();
}




struct S{
    long x;

    this(long x)@safe{
        this.x = x;
    }

    ~this()@safe{
        this.x = -1;
    }

}

void main()@safe{
    auto p = SharedPtr!S.make(42);

    (ref S s){
        assert(s.x == 42);
        p = null;           ///release pointer
        assert(s.x == -1);  ///`s` is dangling reference

    }(p.trustedGet);

}
```

**Comment by joakim-brannstrom** [comment]
Hmm, I see. I understand your point. I would... say that is not using it "correctly" but ya. It can't be machine checked via `@safe` so no automatic guarantee that it doesn't contain any memory corruptions.
I wonder if it would be safe if it was inverted such that "release" is system (thinking).

But your nice trustedGet is OK for me. I'll use that, makes it convenient. It is much better than littering the code with `@trusted` lambdas. It is namely a bit brutal to turn of all safety checks because of a "correct" use of `get`.

```d
// silly example but basically how i'll use it.
void send(T)(ShardPtr!Address addr, T value) {
   if (add && addr.trustedGet.isOpen)
      addr.trustedGet.put(value);
}
```

Maybe you saw the forum thread about system blocks ( https://forum.dlang.org/thread/dmfoucfvatrzzgpzxoza@forum.dlang.org ). That would be nice to have. What they are talking about there is what I mean by "brutal".

**Comment by joakim-brannstrom** [comment]
I'm closing the issue. Thank you for the quick answer
