### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by MANKEYYENAME** [submada/autoptr#4]
Compiler crashes when using `UniquePtr` in `struct`.

```d
import autoptr.unique_ptr;

struct A{
	UniquePtr!int a;
}

void main(){
	A a;
}
```

**Comment by submada** [comment]
Thanks, its bug in compiler, copy ctor cannot be overloaded with template rvalue ctor with this template parameter if struct is used in other struct (maybe something with default copy ctor generator).

I found alternative way to do this and new version is in dub (0.6.0-rc3)
